//
//  SemanticUI.swift
//  Hype
//
//  Copyright © 2018 Nashville Swift Language Group. All rights reserved.
//

import Foundation

public enum SemanticUI: Class {
    case accordion
    case action
    case actions
    case active
    case ad
    case add
    case adjust
    case adn
    case advertisement
    case ae
    case af
    case afghanistan
    case africa
    case african
    case ag
    case ai
    case aid
    case al
    case aland
    case alarm
    case albania
    case algeria
    case align
    case aligned
    case all
    case alphabet
    case alternate
    case am
    case ambulance
    case american
    case an
    case anchor
    case and
    case andorra
    case android
    case angle
    case angola
    case anguilla
    case animated
    case announcement
    case antigua
    case antilles
    case ao
    case apple
    case ar
    case arabia
    case archive
    case argentina
    case armenia
    case arrow
    case article
    case aruba
    case `as`
    case ascending
    case asterisk
    case at
    case attach
    case attached
    case attention
    case au
    case audio
    case australia
    case austria
    case avatar
    case aw
    case ax
    case az
    case azerbaijan
    case ba
    case backward
    case bahamas
    case bahrain
    case ban
    case bangladesh
    case bar
    case barbados
    case barcode
    case bars
    case basic
    case bb
    case bd
    case be
    case beer
    case beg
    case behance
    case belarus
    case belgium
    case belize
    case bell
    case below
    case benin
    case bermuda
    case bf
    case bg
    case bh
    case bhutan
    case bi
    case big
    case bitbucket
    case bitcoin
    case bj
    case black
    case block
    case blue
    case bm
    case bn
    case bo
    case bold
    case bolivia
    case bomb
    case book
    case bookmark
    case bordered
    case borderless
    case bosnia
    case botswana
    case bottom
    case bouvet
    case box
    case br
    case brazil
    case brazzaville
    case breadcrumb
    case briefcase
    case british
    case browse
    case browser
    case brunei
    case bs
    case bsa_cpc
    case bt
    case btc
    case bug
    case building
    case bulgaria
    case bulleted
    case bullhorn
    case bullseye
    case burkina
    case burma
    case burundi
    case button
    case buttons
    case bv
    case bw
    case by
    case bz
    case ca
    case caicos
    case caledonia
    case calendar
    case call
    case cambodia
    case camera
    case cameroon
    case canada
    case cancel
    case cape
    case car
    case card
    case cards
    case caret
    case cart
    case category
    case cayman
    case cc
    case cd
    case celled
    case center
    case central
    case certificate
    case cf
    case cg
    case ch
    case chad
    case chart
    case chat
    case check
    case checkbox
    case checkered
    case checkmark
    case chevron
    case child
    case chile
    case china
    case chinese
    case christmas
    case ci
    case circle
    case circular
    case city
    case ck
    case cl
    case clearing
    case clock
    case clockwise
    case close
    case cloud
    case cm
    case cn
    case co
    case cocktail
    case cocos
    case code
    case codepen
    case coffee
    case cogs
    case collapsing
    case colombia
    case column
    case columns
    case comment
    case comments
    case comoros
    case compact
    case compass
    case complete
    case completed
    case compose
    case compress
    case computer
    case configure
    case congo
    case container
    case content
    case conversation
    case cook
    case copy
    case corner
    case costa
    case cote
    case cr
    case created
    case credit
    case croatia
    case crop
    case crosshairs
    case cs
    case css3
    case cu
    case cuba
    case cube
    case cubes
    case currency
    case cut
    case cv
    case cx
    case cy
    case cyprus
    case cz
    case czech
    case dashboard
    case database
    case date
    case de
    case `default`
    case definition
    case delete
    case delicious
    case demo
    case demos
    case denmark
    case descending
    case description
    case desktop
    case detail
    case deviantart
    case digg
    case dim
    case dimmer
    case direction
    case disabled
    case discussions
    case disk
    case dislike
    case divided
    case divider
    case dividing
    case divoire
    case dj
    case djibouti
    case dk
    case dm
    case `do`
    case doctor
    case dollar
    case dominica
    case dominican
    case dont
    case dot
    case double
    case doubling
    case down
    case download
    case dribbble
    case dropbox
    case dropdown
    case drupal
    case dz
    case ec
    case ecuador
    case edit
    case ee
    case eg
    case egypt
    case eh
    case eight
    case eject
    case el
    case eleven
    case ellipsis
    case emergency
    case empire
    case empty
    case envelope
    case equal
    case equatorial
    case er
    case erase
    case eraser
    case eritrea
    case error
    case es
    case estonia
    case et
    case ethiopia
    case eu
    case eur
    case euro
    case european
    case event
    case example
    case examples
    case excel
    case exchange
    case expand
    case external
    case extinguisher
    case extra
    case eye
    case facebook
    case fade
    case falkland
    case faroe
    case faso
    case fast
    case favorite
    case fax
    case feed
    case female
    case fi
    case field
    case fields
    case fifteen
    case fighter
    case fiji
    case file
    case film
    case filter
    case finland
    case fire
    case first
    case fitted
    case five
    case fixed
    case fj
    case fk
    case flag
    case flask
    case flickr
    case flipped
    case floated
    case floating
    case flowing
    case fluid
    case fm
    case fo
    case folder
    case font
    case food
    case footer
    case fork
    case form
    case forward
    case four
    case foursquare
    case fourteen
    case fr
    case france
    case french
    case friends
    case frown
    case full
    case full_width
    case fullscreen
    case futuna
    case ga
    case gabon
    case gambia
    case game
    case gamepad
    case gb
    case gbp
    case gd
    case ge
    case georgia
    case germany
    case gf
    case gh
    case ghana
    case gi
    case gibraltar
    case gift
    case git
    case github
    case gittip
    case gl
    case globe
    case gm
    case gn
    case google
    case gp
    case gq
    case gr
    case graduation
    case graph
    case greece
    case green
    case greenland
    case grenada
    case grid
    case group
    case grouped
    case gs
    case gt
    case gu
    case guadeloupe
    case guam
    case guatemala
    case guiana
    case guinea
    case guinea_bissau
    case guyana
    case gw
    case gy
    case h
    case hacker
    case haiti
    case half
    case hand
    case handicap
    case hdd
    case header
    case headphone
    case heard
    case heart
    case height
    case helena
    case help
    case hidden
    case hide
    case history
    case hk
    case hm
    case hn
    case home
    case honduras
    case hong
    case horizontal
    case hospital
    case hr
    case ht
    case html5
    case hu
    case huge
    case hungary
    case iceland
    case icon
    case icons
    case id
    case idea
    case ie
    case ignored
    case il
    case image
    case images
    case `in`
    case inbox
    case indent
    case indeterminate
    case india
    case indian
    case indicating
    case indonesia
    case info
    case inline
    case input
    case inr
    case instagram
    case instant
    case introduction
    case inverted
    case io
    case iq
    case ir
    case iran
    case iraq
    case ireland
    case `is`
    case island
    case islands
    case israel
    case it
    case italic
    case italy
    case item
    case items
    case jamaica
    case jan
    case japan
    case jet
    case jm
    case jo
    case joomla
    case jordan
    case jp
    case jpy
    case jsfiddle
    case justify
    case kazakhstan
    case ke
    case kenya
    case key
    case keyboard
    case kg
    case kh
    case ki
    case kingdom
    case kiribati
    case kitts
    case km
    case kn
    case kong
    case korea
    case kp
    case kr
    case krw
    case kuwait
    case kw
    case ky
    case kyrgyzstan
    case kz
    case la
    case lab
    case label
    case labeled
    case language
    case lanka
    case laos
    case laptop
    case large
    case latvia
    case launch
    case layout
    case lb
    case lc
    case leaf
    case lebanon
    case left
    case legal
    case lemon
    case leone
    case lesotho
    case level
    case li
    case liberia
    case libya
    case liechtenstein
    case life
    case lightbulb
    case lightning
    case like
    case link
    case linkedin
    case linkify
    case linux
    case lira
    case list
    case lithuania
    case lk
    case loader
    case loading
    case local
    case location
    case lock
    case log
    case long
    case lr
    case ls
    case lt
    case lu
    case lucia
    case luxembourg
    case lv
    case ly
    case ma
    case macau
    case macedonia
    case madagascar
    case magic
    case magnet
    case magnify
    case mail
    case main
    case malawi
    case malaysia
    case maldives
    case male
    case mali
    case malta
    case map
    case mariana
    case marino
    case marker
    case marshall
    case martinique
    case masked
    case massive
    case masthead
    case mauritania
    case mauritius
    case maxcdn
    case maximize
    case mayen
    case mayotte
    case mc
    case md
    case me
    case medium
    case medkit
    case meh
    case menu
    case message
    case meta
    case mexico
    case mg
    case mh
    case micronesia
    case microphone
    case middle
    case military
    case mini
    case minimal
    case minimize
    case minor
    case minus
    case mk
    case ml
    case mn
    case mo
    case mobile
    case modal
    case moldova
    case monaco
    case money
    case mongolia
    case montenegro
    case montserrat
    case moon
    case morocco
    case move
    case mozambique
    case mp
    case mq
    case mr
    case ms
    case mt
    case mu
    case music
    case mute
    case mv
    case mw
    case mx
    case my
    case mz
    case na
    case name
    case namibia
    case nauru
    case nc
    case ne
    case negative
    case nepal
    case nested
    case netherlands
    case nevis
    case new
    case news
    case nf
    case ng
    case ni
    case nicaragua
    case niger
    case nigeria
    case nine
    case niue
    case nl
    case no
    case norfolk
    case north
    case northern
    case norway
    case notched
    case np
    case nr
    case nu
    case numbered
    case numeric
    case nz
    case ocean
    case off
    case ok
    case ol
    case om
    case oman
    case one
    case open
    case openid
    case options
    case or
    case ordered
    case out
    case outdent
    case outline
    case overflow
    case pa
    case padded
    case page
    case pagelines
    case pakistan
    case palau
    case palestine
    case panama
    case paragraph
    case paraguay
    case paste
    case pause
    case paw
    case payment
    case pdf
    case pe
    case pencil
    case peru
    case pf
    case pg
    case ph
    case philippines
    case phone
    case photo
    case picture
    case pied
    case pierre
    case piled
    case pin
    case pinterest
    case piper
    case pitcairn
    case pk
    case pl
    case plane
    case play
    case plus
    case pm
    case pn
    case point
    case pointing
    case poland
    case polynesia
    case popup
    case portugal
    case position
    case positive
    case pound
    case power
    case powerpoint
    case pr
    case primary
    case print
    case privacy
    case progress
    case protect
    case ps
    case pt
    case puerto
    case pusher
    case puzzle
    case pw
    case py
    case qa
    case qatar
    case qq
    case qrcode
    case question
    case quote
    case radio
    case rain
    case raised
    case random
    case rating
    case re
    case rebel
    case record
    case recycle
    case red
    case reddit
    case refresh
    case relaxed
    case remote
    case remove
    case renren
    case `repeat`
    case reply
    case republic
    case required
    case resize
    case results
    case retro
    case retweet
    case reunion
    case reveal
    case ribbon
    case rica
    case rico
    case right
    case ring
    case ro
    case road
    case rocket
    case romania
    case rotate
    case row
    case rs
    case rss
    case ru
    case rub
    case ruble
    case rupee
    case russia
    case rw
    case rwanda
    case sa
    case sahara
    case saint
    case salvador
    case samoa
    case san
    case sandwich
    case sao
    case saudi
    case save
    case sb
    case sc
    case scrolling
    case sd
    case se
    case search
    case searchable
    case secondary
    case section
    case segment
    case selected
    case selection
    case send
    case senegal
    case serbia
    case setting
    case settings
    case seven
    case seychelles
    case sg
    case sh
    case shaded
    case shape
    case share
    case shield
    case shipping
    case shop
    case shopping
    case show
    case shuffle
    case shutdown
    case shuttle
    case si
    case side
    case sidebar
    case sides
    case sierra
    case sign
    case signal
    case signup
    case singapore
    case sitemap
    case six
    case sixteen
    case sj
    case sk
    case skype
    case sl
    case slack
    case slash
    case slide
    case slider
    case sliders
    case slovakia
    case slovenia
    case sm
    case small
    case smile
    case sn
    case so
    case solomon
    case somalia
    case sort
    case sound
    case soundcloud
    case south
    case space
    case spain
    case spinner
    case spoon
    case spotify
    case square
    case sr
    case sri
    case st
    case stack
    case stackable
    case stacked
    case standard
    case star
    case states
    case statistic
    case statistics
    case steam
    case step
    case steps
    case stop
    case strikethrough
    case striped
    case student
    case stumbleupon
    case styled
    case sub
    case submit
    case `subscript`
    case success
    case sudan
    case suitcase
    case summary
    case sun
    case superscript
    case suriname
    case sv
    case swaziland
    case sweden
    case switzerland
    case sy
    case syria
    case sz
    case tab
    case table
    case tablet
    case tabs
    case tabular
    case tack
    case tag
    case tags
    case taiwan
    case tajikistan
    case talk
    case tanzania
    case target
    case tasks
    case taxi
    case tc
    case td
    case teal
    case ten
    case tencent
    case terminal
    case territories
    case territory
    case tertiary
    case text
    case tf
    case tg
    case th
    case thailand
    case theme
    case thin
    case thirteen
    case three
    case thumb
    case thumbs
    case ticket
    case time
    case timorleste
    case tint
    case tiny
    case title
    case tj
    case tk
    case tl
    case tm
    case tn
    case to
    case toc
    case toggle
    case togo
    case tokelau
    case tome
    case tonga
    case top
    case tr
    case transition
    case translate
    case transparent
    case trash
    case travel
    case treatment
    case tree
    case trello
    case triangle
    case trinidad
    case trophy
    case truck
    case `try`
    case tt
    case tumblr
    case tunisia
    case turkey
    case turkmenistan
    case tuvalu
    case tv
    case tw
    case twelve
    case twitter
    case two
    case tz
    case ua
    case uae
    case ug
    case uganda
    case ui
    case ukraine
    case ul
    case um
    case umbrella
    case underline
    case undo
    case unhide
    case union
    case united
    case university
    case unlink
    case unlock
    case unmute
    case unordered
    case up
    case upload
    case uruguay
    case us
    case usd
    case user
    case users
    case uy
    case uz
    case uzbekistan
    case va
    case value
    case vanuatu
    case vatican
    case vc
    case ve
    case venezuela
    case verde
    case vertical
    case vertically
    case very
    case vg
    case vi
    case video
    case vietnam
    case vimeo
    case vincent
    case vine
    case virgin
    case visible
    case vk
    case vn
    case volume
    case vu
    case wait
    case wallis
    case warning
    case wechat
    case weibo
    case weixin
    case western
    case wf
    case wide
    case width
    case wifi
    case windows
    case winner
    case wizard
    case won
    case word
    case wordpress
    case world
    case wrench
    case write
    case ws
    case x
    case xing
    case yahoo
    case ye
    case yellow
    case yemen
    case yen
    case youtube
    case yt
    case za
    case zambia
    case zealand
    case zimbabwe
    case zip
    case zm
    case zoom
    case zw
    
    public var className: String {
        get { return "\(self)".replacingOccurrences(of: "_", with: "-") }
    }
}
